; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = wt32_p1meter

[env]
lib_deps = 
    ;WifiManager@0.15.0
    PubSubClient@2.8
	ArduinoJson@7.4.1
	xbergcode/DateTimeFunctions@^1.0.0
	ayushsharma82/ElegantOTA @ 3.1.0

[env:wt32-eth01]
platform = espressif32
board = wt32-eth01
monitor_speed = 115200
framework = arduino
